AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
Parameters:
  TableNameParameter:
    Type: String
    Default: "chains"
    Description: store connection identifiers for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: "Required. Can be characters and underscore only. No numbers or special characters allowed."

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: REGIONAL
      StageName: prod

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "index"
          AttributeType: "S"
        - AttributeName: "createdAt"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "index"
          KeyType: "HASH"
        - AttributeName: "createdAt"
          KeyType: "RANGE"

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref TableNameParameter

  ChainHandler:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: create.handler
      Runtime: nodejs12.x
      CodeUri: src/
      Description: chain handler
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          TableName: !Ref TableNameParameter
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableNameParameter
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /chain
            Method: get
            RestApiId:
              Ref: ApiGatewayApi

  IndexHandler:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.hello
      Runtime: nodejs12.x
      CodeUri: src/
      Description: Get handler
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          TableName: !Ref TableNameParameter
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableNameParameter
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /index
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
