AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
Parameters:
  TableNameParameter:
    Type: String
    Default: "VC_chains"
    Description: store full chains. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: "Required. Can be characters and underscore only. No numbers or special characters allowed."

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: REGIONAL
      StageName: prod

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "hash"
          AttributeType: "S"
        - AttributeName: "index"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "hash"
          KeyType: "HASH"
        - AttributeName: "index"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref TableNameParameter

  CheckHandler:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: check.handler
      Runtime: nodejs12.x
      CodeUri: src/
      Description: check handler
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          TableName: !Ref TableNameParameter
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableNameParameter
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /check
            Method: any
            RestApiId:
              Ref: ApiGatewayApi

  BlockHandler:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: block.handler
      Runtime: nodejs12.x
      CodeUri: src/
      Description: Block handler
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          TableName: !Ref TableNameParameter
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableNameParameter
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /block
            Method: any
            RestApiId:
              Ref: ApiGatewayApi
